[package]
name = "mc-rust-server-macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "mc_rust_server_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "*"
syn = { version = "*", features = ["extra-traits"] }
proc-macro2 = "*"
